#!/bin/ksh
SCRIPT_DIR=/adaqfs/halla/adaq/scripts
# 
# Run number - needed by mss storage script
let num=$(eval /adaqfs/halla/adaq/scripts/getrunnumber)
RUNNUMBER_FILE=/adaqfs/halla/adaq/datafile/rcRunNumberL
echo "$num" > $RUNNUMBER_FILE
# 
# New (Feb 8, 2016) scheme to record run info in EPICS

/adaqfs/home/adaq/runinfo/gp_start_runinfo > /dev/null 

#
#
# MLU settings (Modified Oct 23, 2014 by Norman Israel -- epics now logs this information)
#$SCRIPT_DIR/getmlu 
#
# $SCRIPT_DIR/linkassn > /dev/null 2> /dev/null &
#
# reenable scalers if last run died
# $SCRIPT_DIR/clevclr_l
#
# first clean up from previous run (if necessary)
$SCRIPT_DIR/end_clean 
#
# Check that the Pockel Cell HV is correct for this IHWP state.
$SCRIPT_DIR/FlipPCValues
#
PRESCALE=$HOME/prescale/prescaleL.dat       
$SCRIPT_DIR/fileToEvent $PRESCALE 133 
#

$SCRIPT_DIR/epicsRunStart_L &

#
# Launch the scaler logger
$SCRIPT_DIR/getscaler &
#
# These are now separate for left and right HRS 
$SCRIPT_DIR/epicsLogger_L &
$SCRIPT_DIR/fastEpicsLogger_L &
#
# Script to check/restart epics loggers during run
$SCRIPT_DIR/checkEloggers_L &
sleep 5
#exit 0










